name: sigest
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Data Base
  firebase_core: ^1.21.0
  firebase_storage: ^10.3.6
  cloud_firestore: ^3.4.5

  # State Management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  # Auth
  firebase_auth: ^3.6.4
  email_validator: '^2.1.16'

  # Open Link
  url_launcher: ^6.1.5
  flutter_barcode_scanner: ^2.0.0

  # Freezed
  freezed_annotation: ^2.1.0
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  
  # Http
  http: ^0.13.5

  # UI
  cupertino_icons: ^1.0.5
  fluent_ui: ^3.12.0
  readmore: ^2.1.0
  printing: ^5.9.2
  
  # Search
  firestore_search: ^0.1.9
  
  # Responsive
  responsive_framework: ^0.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # Freezed
  freezed: ^2.1.0+1
  build_runner: ^2.2.0

  flutter_lints: ^2.0.0
  
  # Change app name
  change_app_package_name: ^0.1.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icon/

  fonts:
    - family: calibri
      fonts:
        - asset: assets/fonts/calibri/calibri-bold-italic.ttf
        - asset: assets/fonts/calibri/calibri-bold.ttf
        - asset: assets/fonts/calibri/calibri-italic.ttf
        - asset: assets/fonts/calibri/calibri-regular.ttf
    - family: cambria
      fonts:
        - asset: assets/fonts/cambria/Cambria-Font-For Android.ttf
        - asset: assets/fonts/cambria/Cambria-Font-For-Linux.ttf
        - asset: assets/fonts/cambria/Cambria-Font-For-MAC.ttf
        - asset: assets/fonts/cambria/Cambria-Font-For-Windows.ttf
