// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      /* throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        ); */
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfmazh6ZVy4mOuJ6FxNVAidbnkMOuCKQM',
    appId: '1:1060610127963:web:46eb707b68cf07b2eea77e',
    messagingSenderId: '1060610127963',
    projectId: 'sigest-d3347',
    authDomain: 'sigest-d3347.firebaseapp.com',
    storageBucket: 'sigest-d3347.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT63pfXT2uETpuoLOhgkcmpzycRve7GFY',
    appId: '1:1060610127963:android:a845df5562adaca0eea77e',
    messagingSenderId: '1060610127963',
    projectId: 'sigest-d3347',
    storageBucket: 'sigest-d3347.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcLQ7wGeQbV9AY8vp50KNmKewUh1IfC2I',
    appId: '1:1060610127963:ios:62288d54c238d8e4eea77e',
    messagingSenderId: '1060610127963',
    projectId: 'sigest-d3347',
    storageBucket: 'sigest-d3347.appspot.com',
    androidClientId:
        '1060610127963-utmq6d7vl9i8v58pa3q3on2aik3dpr61.apps.googleusercontent.com',
    iosClientId:
        '1060610127963-v8qpdqegk0emtna1anc26r0kjsq4bp1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.sigest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcLQ7wGeQbV9AY8vp50KNmKewUh1IfC2I',
    appId: '1:1060610127963:ios:62288d54c238d8e4eea77e',
    messagingSenderId: '1060610127963',
    projectId: 'sigest-d3347',
    storageBucket: 'sigest-d3347.appspot.com',
    androidClientId:
        '1060610127963-utmq6d7vl9i8v58pa3q3on2aik3dpr61.apps.googleusercontent.com',
    iosClientId:
        '1060610127963-v8qpdqegk0emtna1anc26r0kjsq4bp1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.sigest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfmazh6ZVy4mOuJ6FxNVAidbnkMOuCKQM',
    appId: '1:1060610127963:web:46eb707b68cf07b2eea77e',
    messagingSenderId: '1060610127963',
    projectId: 'sigest-d3347',
    authDomain: 'sigest-d3347.firebaseapp.com',
  );
}
